# Generated by Django 5.1 on 2024-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('StockQuantity', models.IntegerField()),
            ],
        ),
    ]
