# Generated by Django 5.1 on 2024-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='SerialNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
