# Generated by Django 5.1 on 2024-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_addproduct_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
